name: Publish Extension
on:
    pull_request:
        types: [closed]
    workflow_dispatch:

env:
    GIT_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || 'main' }}
    NODE_VERSION: 20.20.0
    PNPM_VERSION: 10.16.0
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs: